# Qasim Shahid SWE 645 - Assignment 4
# deployment.yaml: Kubernetes deployment configuration for the Python Survey application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonsurvey-deployment
  labels:
    app: pythonsurvey
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pythonsurvey
  template:
    metadata:
      labels:
        app: pythonsurvey
    spec:
      containers:
      - name: pythonsurvey
        image: qshahid/pythonsurvey:latest
        ports:
        - containerPort: 8080